# Generated by Django 3.1.2 on 2021-01-30 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=51, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, null=True)),
                ('valor', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_transacao', models.DateField(blank=True, null=True)),
                ('id_remetente', models.IntegerField()),
                ('id_destinatario', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('justificativa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoPremios',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_transacao', models.DateField(blank=True, null=True)),
                ('premio_resgatado', models.IntegerField()),
                ('id_colaborador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('saldo_acumulado', models.IntegerField()),
                ('saldo_recebido', models.IntegerField(null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cargo_colaborador', to='webapi.cargo')),
                ('premios', models.ManyToManyField(blank=True, related_name='premios_colaborador', to='webapi.Premios')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='setor_colaborador', to='webapi.setor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
